# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Zend Talks
tagline:             no idea
url:                 http://janatzend.github.io/
baseurl:             "/"

# About/contact
author:
  name:              Jan Burkl
  url:               https://www.zend.com
  email:             jan@zend.com

gems:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-gist
